// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectCanva() {
  return window['go']['main']['App']['ConnectCanva']();
}

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitEvent'](arg1, arg2);
}

export function ExtractEntities(arg1, arg2) {
  return window['go']['main']['App']['ExtractEntities'](arg1, arg2);
}

export function ExtractFromText(arg1) {
  return window['go']['main']['App']['ExtractFromText'](arg1);
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetCanvaClient() {
  return window['go']['main']['App']['GetCanvaClient']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiagramSteps() {
  return window['go']['main']['App']['GetDiagramSteps']();
}

export function ProcessDiagramStep(arg1) {
  return window['go']['main']['App']['ProcessDiagramStep'](arg1);
}

export function ProcessText(arg1, arg2) {
  return window['go']['main']['App']['ProcessText'](arg1, arg2);
}

export function ResetDiagram() {
  return window['go']['main']['App']['ResetDiagram']();
}

export function SaveProject(arg1, arg2) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording(arg1, arg2) {
  return window['go']['main']['App']['StopRecording'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
