// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {storage} from '../models';
import {ai} from '../models';
import {canva} from '../models';
import {git} from '../models';
import {config} from '../models';
import {models} from '../models';
import {diagram} from '../models';

export function ApplyAppUpdate(arg1:string):Promise<void>;

export function ChangeWhisperModel(arg1:string):Promise<void>;

export function CheckAppUpdate():Promise<updater.UpdateInfo>;

export function CloseCompendium():Promise<void>;

export function ConnectCanva():Promise<void>;

export function ConvertDraftToCompendium(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<storage.CompendiumInfo>;

export function CreateCompendium(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<storage.CompendiumInfo>;

export function CreateCompendiumFile(arg1:string,arg2:string):Promise<void>;

export function CreateCompendiumModule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateJournalEntry(arg1:string,arg2:string):Promise<string>;

export function DeleteCompendiumFile(arg1:string):Promise<void>;

export function DeleteCompendiumModule(arg1:string):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function EmitEvent(arg1:string,arg2:any):Promise<void>;

export function ExtractEntities(arg1:string,arg2:Array<string>):Promise<Array<ai.Entity>>;

export function ExtractFromText(arg1:string):Promise<Array<ai.Entity>>;

export function GenerateCompendiumFromWizard(arg1:storage.WizardConfig):Promise<storage.CompendiumInfo>;

export function GetActiveCompendium():Promise<storage.CompendiumInfo>;

export function GetAppVersion():Promise<string>;

export function GetAudioDevices():Promise<Array<string>>;

export function GetAvailableWhisperModels():Promise<Array<string>>;

export function GetCanvaClient():Promise<canva.CanvaClient>;

export function GetCompendiumModules():Promise<Array<storage.ModuleInfo>>;

export function GetCompendiumStatus():Promise<Array<git.FileStatus>>;

export function GetCompendiumTree():Promise<Array<storage.FileNode>>;

export function GetConfig():Promise<config.Config>;

export function GetDiagramSteps():Promise<string>;

export function GetDownloadedWhisperModels():Promise<Array<string>>;

export function GetFileHistoricalContent(arg1:string,arg2:string):Promise<string>;

export function GetFileTimeline(arg1:string):Promise<Array<git.CommitInfo>>;

export function GetInitialSessionState():Promise<Record<string, any>>;

export function GetJournalEntries():Promise<Array<storage.JournalEntryInfo>>;

export function GetModelCatalogStatus():Promise<Array<models.ModelInfo>>;

export function GetRecentCompendiums():Promise<Array<config.RecentCompendium>>;

export function OpenCompendium(arg1:string):Promise<storage.CompendiumInfo>;

export function ProcessDiagramStep(arg1:string):Promise<string>;

export function ProcessDiagramStepFromMCP(arg1:string):Promise<string>;

export function ProcessText(arg1:string,arg2:boolean):Promise<void>;

export function ReadCompendiumFile(arg1:string):Promise<string>;

export function RenameCompendiumFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ResetDiagram():Promise<void>;

export function RestartApp():Promise<void>;

export function SaveCompendiumFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveDiagramStep(arg1:number,arg2:Array<diagram.Node>,arg3:Array<diagram.Edge>):Promise<boolean>;

export function SaveProject(arg1:string,arg2:string):Promise<string>;

export function SelectFolderDialog(arg1:string):Promise<string>;

export function StartRecording():Promise<void>;

export function StopRecording(arg1:string,arg2:boolean):Promise<string>;

export function TranscribeAudioFile(arg1:string):Promise<string>;

export function StartMicTest(arg1:string):Promise<void>;

export function StopMicTest():Promise<void>;

export function GetAppLogs():Promise<string>;

export function ClearAppLogs():Promise<void>;

export function UpdateCompendiumModule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateDiagramStep(arg1:number,arg2:string):Promise<void>;

export function GetGlobalGraph():Promise<any>;

export function GetChapterGraph(arg1:string):Promise<any>;

export function SaveChapterGraph(arg1:string,arg2:any):Promise<void>;

export function ExtractAndMergeChapterGraph(arg1:string,arg2:string):Promise<any>;

export function GetContextSuggestions(arg1:string):Promise<any>;

export function GetUnassignedTopics():Promise<Array<any>>;

export function CreateUnassignedTopic(arg1:string,arg2:string):Promise<string>;

export function AnalyzeUnassignedPlacement(arg1:string):Promise<any>;

export function PromoteUnassignedTopic(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExtractSelectionToUnassigned(arg1:string,arg2:string,arg3:string):Promise<any>;

export function EmbedUnassignedTopicIntoSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetCurriculumCoherenceMatrix():Promise<any>;

export function GetCurriculumLintReport():Promise<any>;

export function SaveGlobalGraphPositions(arg1:any):Promise<void>;

export function SaveGlobalGraphManualEdge(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteGlobalGraphEdge(arg1:string,arg2:string):Promise<void>;

export function FilterContentForAudience(arg1:string,arg2:string):Promise<string>;

export function DeriveStudentWorksheet(arg1:string,arg2:string):Promise<string>;

export function DeriveSimplifiedVersion(arg1:string,arg2:string):Promise<string>;

export function SaveDerivedLesson(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CalculateSessionPacing(arg1:string,arg2:number,arg3:number):Promise<any>;

export function ExtractCompendiumGlossary():Promise<any>;

export function GenerateGlossaryAsciidoc():Promise<string>;

export function ExtractCompendiumResources():Promise<any>;

export function SaveVoiceMemo(arg1:string,arg2:string,arg3:string):Promise<any>;

export function GetVoiceMemos(arg1:string):Promise<Array<any>>;

export function DeleteVoiceMemo(arg1:string):Promise<void>;

export function GetVoiceMemoAudio(arg1:string):Promise<string>;

export function SaveAsset(arg1:string,arg2:string,arg3:string):Promise<any>;

export function ListCompendiumAssets():Promise<any>;

export function DeleteAsset(arg1:string):Promise<void>;

export function GetAssetBase64(arg1:string):Promise<string>;

export function FormatAsciidocImage(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;





