// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAppUpdate(arg1) {
  return window['go']['main']['App']['ApplyAppUpdate'](arg1);
}

export function ChangeWhisperModel(arg1) {
  return window['go']['main']['App']['ChangeWhisperModel'](arg1);
}

export function CheckAppUpdate() {
  return window['go']['main']['App']['CheckAppUpdate']();
}

export function CloseCompendium() {
  return window['go']['main']['App']['CloseCompendium']();
}

export function ConnectCanva() {
  return window['go']['main']['App']['ConnectCanva']();
}

export function ConvertDraftToCompendium(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConvertDraftToCompendium'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateCompendium(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateCompendium'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateCompendiumFile(arg1, arg2) {
  return window['go']['main']['App']['CreateCompendiumFile'](arg1, arg2);
}

export function CreateCompendiumModule(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCompendiumModule'](arg1, arg2, arg3);
}

export function CreateJournalEntry(arg1, arg2) {
  return window['go']['main']['App']['CreateJournalEntry'](arg1, arg2);
}

export function DeleteCompendiumFile(arg1) {
  return window['go']['main']['App']['DeleteCompendiumFile'](arg1);
}

export function DeleteCompendiumModule(arg1) {
  return window['go']['main']['App']['DeleteCompendiumModule'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitEvent'](arg1, arg2);
}

export function ExtractEntities(arg1, arg2) {
  return window['go']['main']['App']['ExtractEntities'](arg1, arg2);
}

export function ExtractFromText(arg1) {
  return window['go']['main']['App']['ExtractFromText'](arg1);
}

export function GenerateCompendiumFromWizard(arg1) {
  return window['go']['main']['App']['GenerateCompendiumFromWizard'](arg1);
}

export function GetActiveCompendium() {
  return window['go']['main']['App']['GetActiveCompendium']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetAvailableWhisperModels() {
  return window['go']['main']['App']['GetAvailableWhisperModels']();
}

export function GetCanvaClient() {
  return window['go']['main']['App']['GetCanvaClient']();
}

export function GetCompendiumModules() {
  return window['go']['main']['App']['GetCompendiumModules']();
}

export function GetCompendiumStatus() {
  return window['go']['main']['App']['GetCompendiumStatus']();
}

export function GetCompendiumTree() {
  return window['go']['main']['App']['GetCompendiumTree']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiagramSteps() {
  return window['go']['main']['App']['GetDiagramSteps']();
}

export function GetDownloadedWhisperModels() {
  return window['go']['main']['App']['GetDownloadedWhisperModels']();
}

export function GetFileHistoricalContent(arg1, arg2) {
  return window['go']['main']['App']['GetFileHistoricalContent'](arg1, arg2);
}

export function GetFileTimeline(arg1) {
  return window['go']['main']['App']['GetFileTimeline'](arg1);
}

export function GetInitialSessionState() {
  return window['go']['main']['App']['GetInitialSessionState']();
}

export function GetJournalEntries() {
  return window['go']['main']['App']['GetJournalEntries']();
}

export function GetModelCatalogStatus() {
  return window['go']['main']['App']['GetModelCatalogStatus']();
}

export function GetRecentCompendiums() {
  return window['go']['main']['App']['GetRecentCompendiums']();
}

export function OpenCompendium(arg1) {
  return window['go']['main']['App']['OpenCompendium'](arg1);
}

export function ProcessDiagramStep(arg1) {
  return window['go']['main']['App']['ProcessDiagramStep'](arg1);
}

export function ProcessDiagramStepFromMCP(arg1) {
  return window['go']['main']['App']['ProcessDiagramStepFromMCP'](arg1);
}

export function ProcessText(arg1, arg2) {
  return window['go']['main']['App']['ProcessText'](arg1, arg2);
}

export function ReadCompendiumFile(arg1) {
  return window['go']['main']['App']['ReadCompendiumFile'](arg1);
}

export function RenameCompendiumFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameCompendiumFile'](arg1, arg2, arg3);
}

export function ResetDiagram() {
  return window['go']['main']['App']['ResetDiagram']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveCompendiumFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCompendiumFile'](arg1, arg2, arg3);
}

export function SaveDiagramStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDiagramStep'](arg1, arg2, arg3);
}

export function SaveProject(arg1, arg2) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2);
}

export function SelectFolderDialog(arg1) {
  return window['go']['main']['App']['SelectFolderDialog'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording(arg1, arg2) {
  return window['go']['main']['App']['StopRecording'](arg1, arg2);
}

export function TranscribeAudioFile(arg1) {
  return window['go']['main']['App']['TranscribeAudioFile'](arg1);
}

export function StartMicTest(arg1) {
  return window['go']['main']['App']['StartMicTest'](arg1);
}

export function StopMicTest() {
  return window['go']['main']['App']['StopMicTest']();
}

export function GetAppLogs() {
  return window['go']['main']['App']['GetAppLogs']();
}

export function ClearAppLogs() {
  return window['go']['main']['App']['ClearAppLogs']();
}

export function UpdateCompendiumModule(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCompendiumModule'](arg1, arg2, arg3);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateDiagramStep(arg1, arg2) {
  return window['go']['main']['App']['UpdateDiagramStep'](arg1, arg2);
}

export function GetGlobalGraph() {
  return window['go']['main']['App']['GetGlobalGraph']();
}

export function GetChapterGraph(arg1) {
  return window['go']['main']['App']['GetChapterGraph'](arg1);
}

export function SaveChapterGraph(arg1, arg2) {
  return window['go']['main']['App']['SaveChapterGraph'](arg1, arg2);
}

export function ExtractAndMergeChapterGraph(arg1, arg2) {
  return window['go']['main']['App']['ExtractAndMergeChapterGraph'](arg1, arg2);
}

export function GetContextSuggestions(arg1) {
  return window['go']['main']['App']['GetContextSuggestions'](arg1);
}

export function GetUnassignedTopics() {
  return window['go']['main']['App']['GetUnassignedTopics']();
}

export function CreateUnassignedTopic(arg1, arg2) {
  return window['go']['main']['App']['CreateUnassignedTopic'](arg1, arg2);
}

export function AnalyzeUnassignedPlacement(arg1) {
  return window['go']['main']['App']['AnalyzeUnassignedPlacement'](arg1);
}

export function PromoteUnassignedTopic(arg1, arg2, arg3) {
  return window['go']['main']['App']['PromoteUnassignedTopic'](arg1, arg2, arg3);
}

export function ExtractSelectionToUnassigned(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractSelectionToUnassigned'](arg1, arg2, arg3);
}

export function EmbedUnassignedTopicIntoSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['EmbedUnassignedTopicIntoSession'](arg1, arg2, arg3);
}

export function GetCurriculumCoherenceMatrix() {
  return window['go']['main']['App']['GetCurriculumCoherenceMatrix']();
}

export function GetCurriculumLintReport() {
  return window['go']['main']['App']['GetCurriculumLintReport']();
}

export function SaveGlobalGraphPositions(arg1) {
  return window['go']['main']['App']['SaveGlobalGraphPositions'](arg1);
}

export function SaveGlobalGraphManualEdge(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveGlobalGraphManualEdge'](arg1, arg2, arg3);
}

export function DeleteGlobalGraphEdge(arg1, arg2) {
  return window['go']['main']['App']['DeleteGlobalGraphEdge'](arg1, arg2);
}

export function FilterContentForAudience(arg1, arg2) {
  return window['go']['main']['App']['FilterContentForAudience'](arg1, arg2);
}

export function DeriveStudentWorksheet(arg1, arg2) {
  return window['go']['main']['App']['DeriveStudentWorksheet'](arg1, arg2);
}

export function DeriveSimplifiedVersion(arg1, arg2) {
  return window['go']['main']['App']['DeriveSimplifiedVersion'](arg1, arg2);
}

export function SaveDerivedLesson(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDerivedLesson'](arg1, arg2, arg3);
}



